name: CI

on:
  push:
    branches:
      - main
    paths:
      - cmd/**
      - pkg/**
      - go.mod
      - go.sum
  pull_request:
    branches:
      - main
    paths:
      - cmd/**
      - pkg/**
      - go.mod
      - go.sum

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Lint
        uses: golangci/golangci-lint-action@v2

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
